#!/bin/bash
#
# FloatSmith top-level driver script
#

# disable this if you want or need to hard-code the root of this repository
# using a preset environment variable
export FLOATSMITH_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# set tools path
export FLOATSMITH_TOOLS="${FLOATSMITH_HOME}/tools"

echo "==  FloatSmith  =="

# make sure CRAFT is installed and accessible
if ! which craft &>/dev/null; then
    if [ ! -e "${FLOATSMITH_TOOLS}/craft_env.sh" ]; then
        ${FLOATSMITH_TOOLS}/install_craft.sh
    fi
    source ${FLOATSMITH_TOOLS}/craft_env.sh
fi
echo "Using CRAFT executable: $(which craft)"

# make sure ADAPT is installed and accessible
if [[ -z "${ADAPT_HOME}" ]]; then
    if [ ! -e "${FLOATSMITH_TOOLS}/adapt_env.sh" ]; then
        ${FLOATSMITH_TOOLS}/install_adapt.sh
    fi
    source ${FLOATSMITH_TOOLS}/adapt_env.sh
fi
echo "Using CoDiPack located at: ${CODIPACK_HOME}"
echo "Using ADAPT located at: ${ADAPT_HOME}"

# make sure TypeForge is installed and accessible
if ! which typeforge &>/dev/null; then
    if [ ! -e "${FLOATSMITH_TOOLS}/typeforge_env.sh" ]; then
        ${FLOATSMITH_TOOLS}/install_typeforge.sh
    fi
    source ${FLOATSMITH_TOOLS}/typeforge_env.sh
fi
echo "Using TypeForge executable: $(which typeforge)"

# run interactive mode
${FLOATSMITH_HOME}/scripts/wizard.rb

